default['foxtail']['user'] = 'foxtail'
default['foxtail']['group'] = 'foxtail'
default['foxtail']['docroot'] = '/var/www/foxtail'
default['foxtail']['web_port'] = '8080'
default['foxtail']['appUrl'] = 'site.foxtail.com'
default['apache']['servername'] = 'site.foxtail.com'